untitled/comcom/urls.py
from django.urls import path
from . import views

app_name = 'comcom'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('comment/<int:post_pk>/', views.comment_create, name='comment_create'),
    path('reply/<int:comment_pk>/', views.reply_create, name='reply_create'),
]

untitled/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('comment/', include('comcom.urls')),
]

untitled/comcom/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField('記事タイトル', max_length=255)
    text = models.TextField('記事本文')

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField('コメント内容')
    post = models.ForeignKey(Post, verbose_name='対象記事', on_delete=models.CASCADE)
    parent = models.ForeignKey('self', verbose_name='親コメント', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:10]

untitled/comcom/views.py
from django import forms
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic
from .models import Post, Comment

# コメント、返信フォーム
CommentForm = forms.modelform_factory(Comment, fields=('text', ))


class PostList(generic.ListView):
    """記事一覧"""
    model = Post


class PostDetail(generic.DetailView):
    """記事詳細"""
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # どのコメントにも紐づかないコメント=記事自体へのコメント を取得する
        context['comment_list'] = self.object.comment_set.filter(parent__isnull=True)
        return context


def comment_create(request, post_pk):
    """記事へのコメント作成"""
    post = get_object_or_404(Post, pk=post_pk)
    form = CommentForm(request.POST or None)

    if request.method == 'POST':
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        return redirect('comcom:post_detail', pk=post.pk)

    context = {
        'form': form,
        'post': post
    }
    return render(request, 'comcom/comment_form.html', context)


def reply_create(request, comment_pk):
    """コメントへの返信"""
    comment = get_object_or_404(Comment, pk=comment_pk)
    post = comment.post
    form = CommentForm(request.POST or None)

    if request.method == 'POST':
        reply = form.save(commit=False)
        reply.parent = comment
        reply.post = post
        reply.save()
        return redirect('comcom:post_detail', pk=post.pk)

    context = {
        'form': form,
        'post': post,
        'comment': comment,
    }
    return render(request, 'comcom/comment_form.html', context)

untitled/comcom/templates/comcom/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
{% block content %}
{% endblock %}
</body>
</html>

untitled/comcom/templates/comcom/comment_form.html
{% extends 'comcom/base.html' %}

{% block content %}
    <section class="section">
        <div class="container">
            <form action="" method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <button type="submit">送信</button>
                <h1>
                    ＊＊＊名前を入力してください＊＊＊
                </h1>
            </form>
        </div>
    </section>
{% endblock %}

untitled/comcom/templates/comcom/post_detail.html
{% extends 'comcom/base.html' %}

{% block content %}
<a href="{% url 'comcom:post_list' %}">戻る</a>
<hr>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
<meta charset="utf-8">
    <title>Places Search Box</title>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #description {
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
      }

      #infowindow-content .title {
        font-weight: bold;
      }

      #infowindow-content {
        display: none;
      }

      #map #infowindow-content {
        display: inline;
      }

      .pac-card {
        margin: 10px 10px 0 0;
        border-radius: 2px 0 0 2px;
        box-sizing: border-box;
        -moz-box-sizing: border-box;
        outline: none;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        background-color: #fff;
        font-family: Roboto;
      }

      #pac-container {
        padding-bottom: 12px;
        margin-right: 12px;
      }

      .pac-controls {
        display: inline-block;
        padding: 5px 11px;
      }

      .pac-controls label {
        font-family: Roboto;
        font-size: 13px;
        font-weight: 300;
      }

      #pac-input {
        background-color: #fff;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        margin-left: 12px;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 130px;
      }

      #pac-input:focus {
        border-color: #4d90fe;
      }

      #title {
        color: #fff;
        background-color: #4d90fe;
        font-size: 25px;
        font-weight: 500;
        padding: 6px 12px;
      }
      #target {
        width: 345px;
      }
    </style>
  </head>
  <body>
    <input id="pac-input" class="controls" type="text" placeholder="Search Box">
    <div id="map"></div>
    <script>

      function initAutocomplete() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 33.10, lng: 131.32},
          zoom: 10,
          mapTypeId: 'hybrid',
	  mapTypeControl: false,
 	 fullscreenControl: true, //全画面表示コントロール
	 fullscreenControlOptions: {
              position: google.maps.ControlPosition.LEFT_BOTTOM
         },
	 streetViewControl: true, //ストリートビュー コントロール
 	 zoomControl: false, //ズーム コントロール
        });

	map.addListener('click', function(e) {
	  getClickLatLng(e.latLng, map);
        });

      function getClickLatLng(lat_Lng, map) {

      // マーカーを設置
      var marker = new google.maps.Marker({
        position: lat_Lng,
        map: map
      });

      //  情報ウィンドウ

      var lat_lat = lat_Lng.lat();
      var lng_lng = lat_Lng.lng();

      var contentStr_lat = String(lat_lat);
      var contentStr_lng = String(lng_lng);

      var contentStr = contentStr_lat + ',' + contentStr_lng

      var infowindow = new google.maps.InfoWindow({
          content: contentStr
      });

      infowindow.open(map, marker);

      // 座標の中心をずらす
      map.panTo(lat_Lng);
      }


        // 検索ボックスの設定
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_CENTER].push(input);

        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

        var markers = [];

        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length == 0) {
            return;
          }

          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            if (!place.geometry) {
              console.log("Returned place contains no geometry");
              return;
            }
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(0, 0),
              scaledSize: new google.maps.Size(25, 25)
            };

            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });
      }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBsZ3XWGHLLDQdWveKBAhOae-JcwKiPgUM&libraries=places&callback=initAutocomplete"
         async defer></script>
<a href="{% url 'comcom:comment_create' post.pk %}">コメントする</a>

<hr>
<h2 class="title is-5">コメント一覧</h2>
{% for comment in comment_list %}
<div class="box">
    <p>{{ comment.text }}</p>
    <a href="{% url 'comcom:reply_create' comment.pk %}">返信する</a>
    {% with reply_list=comment.comment_set.all %}
    {% include 'comcom/includes/reply.html' %}
    {% endwith %}
</div>
{% endfor %}
{% endblock %}

untitled/comcom/templates/comcom/post_list.html
{% extends 'comcom/base.html' %}

{% block content %}
    <section class="section">
        <div class="container">
            {% for post in post_list %}
                <a href="{% url 'comcom:post_detail' post.pk %}">
                    <div class="box">
                        <p>{{ post.title }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
    </section>
{% endblock %}